name: Main CI

on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/API-OGE:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: ${{ env.IMAGE_NAME }}
          path: app/artifacts/.
      - name: Push artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ${{ steps.extract.outputs.destination }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ${{ steps.extract.outputs.destination }} # The folder the action should deploy.
